distro: trusty
sudo: true
language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
script:
  - git clone https://github.com/catchorg/Catch2.git
  - cd Catch2
  - cmake -Bbuild -H. -DCMAKE_INSTALL_PREFIX:PATH=/usr -DBUILD_TESTING=OFF
  - cmake --build build/
  - cd build && sudo make install
  - cd ../..
  - CXX=/usr/bin/g++-7 && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_DIR=. ../ && make && make test
