#!/bin/bash

set -e

if [[ ! -f "bin/vault" ]]; then
    mkdir -p bin

    pushd bin

    curl -O -L https://releases.hashicorp.com/vault/1.3.0/vault_1.3.0_linux_amd64.zip
    unzip vault_1.3.0_linux_amd64.zip
    rm vault_1.3.0_linux_amd64.zip

    popd
fi
