#!/bin/bash

export VAULT_ADDR=http://127.0.0.1:8200
TOKEN=$(grep Root operator.txt | awk '{print $4}')

VAULT_TOKEN=$TOKEN bin/vault secrets enable -version=2 -path=secret kv
VAULT_TOKEN=$TOKEN bin/vault secrets enable -version=1 -path=legacy kv
