#!/bin/bash

export VAULT_ADDR=http://127.0.0.1:8200
TOKEN=$(grep Root operator.txt | awk '{print $4}')

VAULT_TOKEN=$TOKEN bin/vault kv put secret/hello foo=bar
VAULT_TOKEN=$TOKEN bin/vault kv put legacy/hello foo=bar
