#!/bin/sh

export VAULT_ADDR=http://127.0.0.1:8200

TOKEN=$(grep Root operator.txt | awk '{print $4}')

VAULT_TOKEN=$TOKEN bin/vault write auth/approle/role/client policies="example"
ROLE_ID=$(VAULT_TOKEN=$TOKEN bin/vault read auth/approle/role/client/role-id | grep role_id | awk '{print $2}')
SECRET_ID=$(VAULT_TOKEN=$TOKEN bin/vault write -f auth/approle/role/client/secret-id | grep -m1 secret_id | awk '{print $2}')

rm -f .env

echo "export VAULT_SINGLE_TOKEN=$TOKEN" >> .env
echo "export APPROLE_ROLE_ID=$ROLE_ID" >> .env
echo "export APPROLE_SECRET_ID=$SECRET_ID" >> .env
