#!/bin/sh

export VAULT_ADDR=http://127.0.0.1:8200

TOKEN=$(grep Root operator.txt | awk '{print $4}')
ROLE_ID=$(VAULT_TOKEN=$TOKEN bin/vault read auth/approle/role/client/role-id | grep role_id | awk '{print $2}')
WRAPPED_TOKEN=$(VAULT_TOKEN=$TOKEN bin/vault write -wrap-ttl=100s -f auth/approle/role/client/secret-id | grep -m1 wrapping_token | awk '{print $2}')

rm -f .wrapped_env

echo "export APPROLE_ROLE_ID=$ROLE_ID" >> .wrapped_env
echo "export APPROLE_WRAPPED_TOKEN=$WRAPPED_TOKEN" >> .wrapped_env
