add_library(vault
        include/VaultClient.h
        src/auth/AliCloud.cpp
        src/auth/AppRole.cpp
        src/auth/AWS.cpp
        src/auth/Azure.cpp
        src/auth/CloudFoundry.cpp
        src/auth/GitHub.cpp
        src/auth/GoogleCloud.cpp
        src/auth/JwtOidc.cpp
        src/auth/Kerberos.cpp
        src/auth/Kubernetes.cpp
        src/auth/Ldap.cpp
        src/auth/OCI.cpp
        src/auth/Okta.cpp
        src/auth/Radius.cpp
        src/auth/Tls.cpp
        src/auth/UserPass.cpp
        src/auth/strategies/AppRoleStrategy.cpp
        src/auth/strategies/JwtStrategy.cpp
        src/auth/strategies/LdapStrategy.cpp
        src/auth/strategies/TlsStrategy.cpp
        src/auth/strategies/WrappedSecretAppRoleStrategy.cpp
        src/domain/VaultClient.cpp
        src/domain/ConfigBuilder.cpp
        src/engines/ActiveDirectory.cpp
        src/engines/AliCloud.cpp
        src/engines/AWS.cpp
        src/engines/Azure.cpp
        src/engines/Consul.cpp
        src/engines/Cubbyhole.cpp
        src/engines/Database.cpp
        src/engines/GoogleCloud.cpp
        src/engines/GoogleCloudKms.cpp
        src/engines/identity/Entity.cpp
        src/engines/identity/EntityAlias.cpp
        src/engines/identity/Group.cpp
        src/engines/identity/GroupAlias.cpp
        src/engines/identity/IdentityTokens.cpp
        src/engines/identity/Lookup.cpp
        src/engines/KeyValue.cpp
        src/engines/Kmip.cpp
        src/engines/MongoDBAtlas.cpp
        src/engines/Nomad.cpp
        src/engines/OpenLDAP.cpp
        src/engines/Pki.cpp
        src/engines/RabbitMq.cpp
        src/engines/SSH.cpp
        src/engines/Totp.cpp
        src/engines/Transform.cpp
        src/engines/Transit.cpp
        src/support/Base64.cpp
        src/support/HttpClient.cpp
        src/support/HttpConsumer.cpp
        src/system/auth/Auth.cpp
        src/system/audit/Audit.cpp
        src/system/auditing/Auditing.cpp
        src/system/config/ControlGroup.cpp
        src/system/config/Cors.cpp
        src/system/config/UI.cpp
        src/system/counters/Counters.cpp
        src/system/generate_root/GenerateRoot.cpp
        src/system/init/Init.cpp
        src/system/leases/Leases.cpp
        src/system/license/License.cpp
        src/system/mfa/Duo.cpp
        src/system/mfa/Mfa.cpp
        src/system/mfa/Okta.cpp
        src/system/mfa/PingId.cpp
        src/system/mfa/Totp.cpp
        src/system/mounts/Mounts.cpp
        src/system/namespaces/Namespaces.cpp
        src/system/plugins/Plugins.cpp
        src/system/policy/Policy.cpp
        src/system/policies/Policies.cpp
        src/system/policies/ACL.cpp
        src/system/policies/EGP.cpp
        src/system/policies/RGP.cpp
        src/system/pprof/Pprof.cpp
        src/system/raw/Raw.cpp
        src/system/sealwrap/Sealwrap.cpp
        src/system/tools/Tools.cpp
        src/system/Sys.cpp
        src/auth/Tokens.cpp)